remote_theme: vaibhavvikas/jekyll-theme-minimalistic
color-scheme: light

title: mbta-park-access
description: A system‑wide assessment of transit‑based park access in Boston urban core, identifying gaps and opportunities for equitable pedestrian infrastructure.

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

navigation:
  - name: Read me
    link: ./index.html
  - name: Executive Summary
    link: ./executive-summary
  - name: Mapping workflow
    link: ./analysis
